cpu-bind=MASK - bp1-compute098, task  0  0 [1542801]: mask 0x80000080000 set
Traceback (most recent call last):
  File "/user/home/zj22662/photon-net/calc_test_loss.py", line 47, in <module>
    iterate_models(output_folder, results_subfolder, input_config)
  File "/user/home/zj22662/photon-net/calc_test_loss.py", line 37, in iterate_models
    utils.evaluate_and_save_test_loss(
  File "/user/home/zj22662/photon-net/p_pack/utils.py", line 125, in evaluate_and_save_test_loss
    setattr(g, name, g_data[name])
                     ~~~~~~^^^^^^
  File "/user/home/zj22662/photon-net/venv2/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py", line 254, in __getitem__
    return format.read_array(bytes,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/zj22662/photon-net/venv2/lib/python3.12/site-packages/numpy/lib/format.py", line 815, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
